timeout: 0
serial: yes
serial_baudrate: 38400

/LLPL Limine Bare-Metal Demo
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/initrd.tar
    module_string: initrd.tar
    resolution: 1024x768x32
